import Card from "../Components/Card";

const Read = ()=>{
    return (
        <div>
        <br/>
      
        <div className="mx-1 grid md:grid-cols-2 lg:grid-cols-3 max-w-[1240px] font-bold md:mx-auto lg:mx-auto md:mt-3 md:px-0">
            <Card title="What is Blog?" author="MDfazil" note="A blog, short for weblog, is a frequently updated web page used for personal commentary or business content. Blogs are often interactive and include sections at the bottom of individual blog posts where readers can leave comments.

Most are written in a conversational style to reflect the voice and personal views of the blogger. Some businesses use blogs to connect with target audiences and sell products.

Blogs were originally called weblogs, which were websites that consisted of a series of entries arranged in reverse chronological order, so the newest posts appeared at the top. They were frequently updated with new information about various topics."/>
            <Card title="Card 2" author="MDfazil"note="Consectetur adipiscindcdvdvd vdmvd dvdvd dvkd dcdscdc dscdvevdvs vsdvsdvsvsdvsdvsdv svsdvsvsvsvs vsdvsdvsvsdvsdv svsdvsdvsdvsv sdvsdvsdvsdvsdvsd vsdvsdvsdvsdvsdv sdvsdvsdvsv sdvv ebrsg bscvbfs bsf gsfbgrwbfs bfs bgsbsbgffgb fsgbfbfsgbdfgbb dbfgbdfbgdfbdfbdf bfdbggfbgddf bgdfgbdfbgdbdfbdfbfg bfgbfbdfbdfgbdf bgfbgdfbdfbdf bdfbdfbdfb gfbfgbfbgbfd bfgbdfb dcdvdvd vdmvd dvdvd dvkd dcdscdc dscdvevdvs vsdvsdvsvsdvsdvsdv svsdvsvsvsvs vsdvsdvsvsdvsdv svsdvsdvsdvsv sdvsdvsdvsdvsdvsd vsdvsdvsdvsdvsdv sdvsdvsdvsv sdvv ebrsg bscvbfs bsf gsfbgrwbfs bfs bgsbsbgffgb fsgbfbfsgbdfgbb dbfgbdfbgdfbdfbdf bfdbggfbgddf bgdfgbdfbgdbdfbdfbfg bfgbfbdfbdfgbdf bgfbgdfbdfbdf bdfbdfbdfb gfbfgbfbgbfd bfgbdfbssg elit."/>
            <Card title="Card 3" author="MDfazil" note="Fusce faucibus arcu eget tur dcdvdvd vdmvd dvdvd dvkd dcdscdc dscdvevdvs vsdvsdvsvsdvsdvsdv svsdvsvsvsvs vsdvsdvsvsdvsdv svsdvsdvsdvsv sdvsdvsdvsdvsdvsd vsdvsdvsdvsdvsdv sdvsdvsdvsv sdvv ebrsg bscvbfs bsf gsfbgrwbfs bfs bgsbsbgffgb fsgbfbfsgbdfgbb dbfgbdfbgdfbdfbdf bfdbggfbgddf bgdfgbdfbgdbdfbdfbfg bfgbfbdfbdfgbdf bgfbgdfbdfbdf bdfbdfbdfb gfbfgbfbgbfd bfgbdfb dcdvdvd vdmvd dvdvd dvkd dcdscdc dscdvevdvs vsdvsdvsvsdvsdvsdv svsdvsvsvsvs vsdvsdvsvsdvsdv svsdvsdvsdvsv sdvsdvsdvsdvsdvsd vsdvsdvsdvsdvsdv sdvsdvsdvsv sdvv ebrsg bscvbfs bsf gsfbgrwbfs bfs bgsbsbgffgb fsgbfbfsgbdfgbb dbfgbdfbgdfbdfbdf bfdbggfbgddf bgdfgbdfbgdbdfbdfbfg bfgbfbdfbdfgbdf bgfbgdfbdfbdf bdfbdfbdfb gfbfgbfbgbfd bfgbdfbsspis bibendum." />
            <Card title="Hi thidjcdc" author="MDfazil" note="dcdvdvd vdmvd dvdvd dcdvdvd vdmvd dvdvd dvkd dcdscdc dscdvevdvs vsdvsdvsvsdvsdvsdv svsdvsvsvsvs vsdvsdvsvsdvsdv svsdvsdvsdvsv sdvsdvsdvsdvsdvsd vsdvsdvsdvsdvsdv sdvsdvsdvsv sdvv ebrsg bscvbfs bsf gsfbgrwbfs bfs bgsbsbgffgb fsgbfbfsgbdfgbb dbfgbdfbgdfbdfbdf bfdbggfbgddf bgdfgbdfbgdbdfbdfbfg bfgbfbdfbdfgbdf bgfbgdfbdfbdf bdfbdfbdfb gfbfgbfbgbfd bfgbdfb dcdvdvd vdmvd dvdvd dvkd dcdscdc dscdvevdvs vsdvsdvsvsdvsdvsdv svsdvsvsvsvs vsdvsdvsvsdvsdv svsdvsdvsdvsv sdvsdvsdvsdvsdvsd vsdvsdvsdvsdvsdv sdvsdvsdvsv sdvv ebrsg bscvbfs bsf gsfbgrwbfs bfs bgsbsbgffgb fsgbfbfsgbdfgbb dbfgbdfbgdfbdfbdf bfdbggfbgddf bgdfgbdfbgdbdfbdfbfg bfgbfbdfbdfgbdf bgfbgdfbdfbdf bdfbdfbdfb gfbfgbfbgbfd bfgbdfbss dvkd"/>
            <Card title="Card 2" author="MDfazil" note="Consectetur adipiscing dcdvdvd vdmvd dvdvd dvkd dcdscdc dscdvevdvs vsdvsdvsvsdvsdvsdv svsdvsvsvsvs vsdvsdvsvsdvsdv svsdvsdvsdvsv sdvsdvsdvsdvsdvsd vsdvsdvsdvsdvsdv sdvsdvsdvsv sdvv ebrsg bscvbfs bsf gsfbgrwbfs bfs bgsbsbgffgb fsgbfbfsgbdfgbb dbfgbdfbgdfbdfbdf bfdbggfbgddf bgdfgbdfbgdbdfbdfbfg bfgbfbdfbdfgbdf bgfbgdfbdfbdf bdfbdfbdfb gfbfgbfbgbfd bfgbdfb dcdvdvd vdmvd dvdvd dvkd dcdscdc dscdvevdvs vsdvsdvsvsdvsdvsdv svsdvsvsvsvs vsdvsdvsvsdvsdv svsdvsdvsdvsv sdvsdvsdvsdvsdvsd vsdvsdvsdvsdvsdv sdvsdvsdvsv sdvv ebrsg bscvbfs bsf gsfbgrwbfs bfs bgsbsbgffgb fsgbfbfsgbdfgbb dbfgbdfbgdfbdfbdf bfdbggfbgddf bgdfgbdfbgdbdfbdfbfg bfgbfbdfbdfgbdf bgfbgdfbdfbdf bdfbdfbdfb gfbfgbfbgbfd bfgbdfbsselit." />
            <Card title="Card 3" author="MDfazil" note="Fusce faucibus arcu eget turpis bibendum." />
            <Card title="Hi thidjcdc" author="MDfazil" note="dcdvdvd vdmv dcdvdvd vdmvd dvdvd dvkd dcdscdc dscdvevdvs vsdvsdvsvsdvsdvsdv svsdvsvsvsvs vsdvsdvsvsdvsdv svsdvsdvsdvsv sdvsdvsdvsdvsdvsd vsdvsdvsdvsdvsdv sdvsdvsdvsv sdvv ebrsg bscvbfs bsf gsfbgrwbfs bfs bgsbsbgffgb fsgbfbfsgbdfgbb dbfgbdfbgdfbdfbdf bfdbggfbgddf bgdfgbdfbgdbdfbdfbfg bfgbfbdfbdfgbdf bgfbgdfbdfbdf bdfbdfbdfb gfbfgbfbgbfd bfgbdfb dcdvdvd vdmvd dvdvd dvkd dcdscdc dscdvevdvs vsdvsdvsvsdvsdvsdv svsdvsvsvsvs vsdvsdvsvsdvsdv svsdvsdvsdvsv sdvsdvsdvsdvsdvsd vsdvsdvsdvsdvsdv sdvsdvsdvsv sdvv ebrsg bscvbfs bsf gsfbgrwbfs bfs bgsbsbgffgb fsgbfbfsgbdfgbb dbfgbdfbgdfbdfbdf bfdbggfbgddf bgdfgbdfbgdbdfbdfbfg bfgbfbdfbdfgbdf bgfbgdfbdfbdf bdfbdfbdfb gfbfgbfbgbfd bfgbdfbssd dvdvd dvkd"/>
            <Card title="Card 2" author="MDfazil" note="Consectetur adipiscing elit." />
            <Card title="Card 3" author="MDfazil" note="Fusce faucibus arcu edcdvdvd vdmvd dvdvd dvkd dcdscdc dscdvevdvs vsdvsdvsvsdvsdvsdv svsdvsvsvsvs vsdvsdvsvsdvsdv svsdvsdvsdvsv sdvsdvsdvsdvsdvsd vsdvsdvsdvsdvsdv sdvsdvsdvsv sdvv ebrsg bscvbfs bsf gsfbgrwbfs bfs bgsbsbgffgb fsgbfbfsgbdfgbb dbfgbdfbgdfbdfbdf bfdbggfbgddf bgdfgbdfbgdbdfbdfbfg bfgbfbdfbdfgbdf bgfbgdfbdfbdf bdfbdfbdfb gfbfgbfbgbfd bfgbdfb dcdvdvd vdmvd dvdvd dvkd dcdscdc dscdvevdvs vsdvsdvsvsdvsdvsdv svsdvsvsvsvs vsdvsdvsvsdvsdv svsdvsdvsdvsv sdvsdvsdvsdvsdvsd vsdvsdvsdvsdvsdv sdvsdvsdvsv sdvv ebrsg bscvbfs bsf gsfbgrwbfs bfs bgsbsbgffgb fsgbfbfsgbdfgbb dbfgbdfbgdfbdfbdf bfdbggfbgddf bgdfgbdfbgdbdfbdfbfg bfgbfbdfbdfgbdf bgfbgdfbdfbdf bdfbdfbdfb gfbfgbfbgbfd bfgbdfbssget turpis bibendum." />
        </div>
        <br/>
        </div>
    );
}

export default Read;